---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: apicart
  namespace: default
  labels:
    app: apicart
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicart
  template:
    metadata:
      name: apicart
      labels:
        app: apicart
    spec:
      containers:
      - name: apicart
        image: us.gcr.io/just-slate-88918/api_cart_dev2:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: DEV2
        - name: eureka_instance_hostname
          value: 'IP'
        resources: {}
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "-o", "nonempty", "cart_vol", "/var/log/logback"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/var/log/logback"]
      restartPolicy: Always
      hostAliases:
      - ip: 35.202.220.122
        hostnames:
        - wcs.academy.com
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
      - name: aso-gcr-secret
      schedulerName: default-scheduler
  strategy:
    type: Recreate
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apicart
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: apicart
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
