---
kind: Service
apiVersion: v1
metadata:
  name: apicart
  namespace: qa2
  labels:
    app: apicart
spec:
  ports:
  - name: tcp-11001-11001-apicart
    protocol: TCP
    port: 11001
    targetPort: 11001
  selector:
    app: apicart
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
